export enum GameState {
  LOBBY = 0,
  MASK_DRAW = 1,
  MASK_COMPARISON = 2,
  SCORING = 3,
  BALLROOM = 4,
  USER_SELECT = 5,

  CUTSCENE_OPENING = 100,
  CUTSCENE_MAKE_THE_MASK = 101,
  CUTSCENE_THE_CHOICE = 102,
}
